name: Test SDK & UI

env:
  CI: true
  FORCE_COLOR: true

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install --frozen-lockfile
      - run: yarn build

      - name: Test SDK & UI
        run: yarn test

      - name: Test SDK integration against live contracts
        if: ${{ github.ref == 'refs/heads/master' }}
        run: yarn test-live
